# name: Ejecutar procesar_y_guardar_db.py 4 veces al dÃ­a

#on:
 # schedule:
    # 00:00, 06:00, 12:00 y 18:00 Argentina (03:00, 09:00, 15:00, 21:00 UTC)
  #  - cron: "0 3,9,15,21 * * *"
  #workflow_dispatch:

#jobs:
 # run-script:
  #  runs-on: ubuntu-latest

   # steps:
    #  - name: Clonar el repositorio
     #   uses: actions/checkout@v4

      #- name: Configurar Python
       # uses: actions/setup-python@v5
        #with:
         # python-version: "3.10"

      #- name: Instalar dependencias
       # run: |
        #  cd backend
         # pip install -r requirements.txt

#      - name: Crear archivo .env
 #       run: |
  #        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> backend/.env
   #       echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> backend/.env
    #      echo "GNEWS_API_KEY=${{ secrets.GNEWS_API_KEY }}" >> backend/.env
     #     echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> backend/.env
      #    echo "ENVIRONMENT=production" >> backend/.env

      #- name: Ejecutar script
       # run: |
        #  cd backend
         # python procesar_y_guardar_db.py */ 
